"""stage2 initial tables

Revision ID: 549464ecbd93
Revises: 
Create Date: 2026-09-16 02:07:51.898842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '549464ecbd93'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_question_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("language IN ('id','en')", name='ck_session_language'),
    sa.CheckConstraint("status IN ('draft','ready','in_progress','completed','abandoned')", name='ck_session_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_created_at', 'interview_sessions', ['created_at'], unique=False)
    op.create_index('idx_session_status', 'interview_sessions', ['status'], unique=False)
    op.create_table('final_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('scores_per_competency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_evaluations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disclaimer', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('complete','incomplete')", name='ck_report_status'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id'),
    sa.UniqueConstraint('session_id', 'version', name='uq_report_session_version')
    )
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('competency', sa.String(length=100), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('expected_evidence', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parent_question_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy','medium','hard')", name='ck_question_difficulty'),
    sa.CheckConstraint("kind IN ('main','follow_up')", name='ck_question_kind'),
    sa.CheckConstraint('order_index >= 0 AND order_index <= 4', name='ck_question_order'),
    sa.ForeignKeyConstraint(['parent_question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_question_id'),
    sa.UniqueConstraint('session_id', 'order_index', name='uq_question_session_order')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mime_type = 'application/pdf'", name='ck_document_mime'),
    sa.CheckConstraint("status IN ('uploaded','processing','ready','failed')", name='ck_document_status'),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_document_file_size'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('candidate_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(answer_text) > 0', name='ck_answer_text_not_empty'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_answer_session_question')
    )
    op.create_table('answer_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('relevance', sa.SmallInteger(), nullable=False),
    sa.Column('technical_accuracy', sa.SmallInteger(), nullable=False),
    sa.Column('clarity', sa.SmallInteger(), nullable=False),
    sa.Column('evidence_specificity', sa.SmallInteger(), nullable=False),
    sa.Column('structure', sa.SmallInteger(), nullable=False),
    sa.Column('overall', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_quote', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('improvements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rubric_version', sa.String(length=20), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('evaluated','needs_review','insufficient_answer')", name='ck_eval_status'),
    sa.CheckConstraint('clarity >= 0 AND clarity <= 5', name='ck_eval_clarity'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_eval_confidence'),
    sa.CheckConstraint('evidence_specificity >= 0 AND evidence_specificity <= 5', name='ck_eval_evidence'),
    sa.CheckConstraint('overall >= 0 AND overall <= 5', name='ck_eval_overall'),
    sa.CheckConstraint('relevance >= 0 AND relevance <= 5', name='ck_eval_relevance'),
    sa.CheckConstraint('structure >= 0 AND structure <= 5', name='ck_eval_structure'),
    sa.CheckConstraint('technical_accuracy >= 0 AND technical_accuracy <= 5', name='ck_eval_accuracy'),
    sa.ForeignKeyConstraint(['answer_id'], ['candidate_answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_evaluations')
    op.drop_table('candidate_answers')
    op.drop_table('source_documents')
    op.drop_table('interview_questions')
    op.drop_table('final_reports')
    op.drop_index('idx_session_status', table_name='interview_sessions')
    op.drop_index('idx_session_created_at', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
